import unittest
from io import StringIO

from src.scanner import EndOfFileError, Scanner, SourceLocation, Token, TokenType


class TestScanner(unittest.TestCase):
    def test_get_token(self):
        scanner = Scanner(
            StringIO(
                """\
// comment1
component NormalPostbackInfo as "回传信息规整"
{
    unit MmpNameInfo as "MMP名信息"
    {
        switch get("RawPostbackInfo_ThreeType") as "aaa" {
        case "kochava" as "bbb", "min_kochava" as "cccc":
            return transform(`TODO Kochava`) as "Kochava MMP" // comment2
        default:
            return transform(`TODO` + " other") as "其他MMP"
        }
    }

    unit AttributeTypeInfo as "归因类型信息"
    {
        if test("NormalPostbackInfo_MmpNameInfo_Value", "eq", "Kochava") as "aaa" {

            if test("RawPostbackInfo_HasAttribuType", "eq", "true") as "ccc"
               && test("RawPostbackInfo_AttribuType", "eq", "") as "ddd" {

                return transform(`TODO 0`) as "非mtg归因 - kochava"
            }
        }

        // comment3
        if test("RawPostbackInfo_AttribuType", "eq", "0") as "eeee" {
                return transform(`TODO 0`) as "非mtg归因 - 其他"
        }

        return transform(`TODO 1`) as "mtg归因"
    }
}
"""
            )
        )

        tokens = []
        while True:
            try:
                t = scanner.get_token()
            except EndOfFileError:
                break
            tokens.append(t)

        self.assertEqual(
            tokens,
            [
                Token(
                    type=TokenType.COMMENT,
                    data="/// comment1\n",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=0,
                        line_number=1,
                        column_number=1,
                    ),
                ),
                Token(
                    type=TokenType.COMPONENT_KEYWORD,
                    data="component",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=12,
                        line_number=2,
                        column_number=1,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=21,
                        line_number=2,
                        column_number=10,
                    ),
                ),
                Token(
                    type=TokenType.IDENTIFIER,
                    data="NormalPostbackInfo",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=22,
                        line_number=2,
                        column_number=11,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=40,
                        line_number=2,
                        column_number=29,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=41,
                        line_number=2,
                        column_number=30,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=43,
                        line_number=2,
                        column_number=32,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"回传信息规整"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=44,
                        line_number=2,
                        column_number=33,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=52,
                        line_number=2,
                        column_number=41,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_BRACE,
                    data="{",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=53,
                        line_number=3,
                        column_number=1,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n    ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=54,
                        line_number=3,
                        column_number=2,
                    ),
                ),
                Token(
                    type=TokenType.UNIT_KEYWORD,
                    data="unit",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=59,
                        line_number=4,
                        column_number=5,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=63,
                        line_number=4,
                        column_number=9,
                    ),
                ),
                Token(
                    type=TokenType.IDENTIFIER,
                    data="MmpNameInfo",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=64,
                        line_number=4,
                        column_number=10,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=75,
                        line_number=4,
                        column_number=21,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=76,
                        line_number=4,
                        column_number=22,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=78,
                        line_number=4,
                        column_number=24,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"MMP名信息"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=79,
                        line_number=4,
                        column_number=25,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n    ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=87,
                        line_number=4,
                        column_number=33,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_BRACE,
                    data="{",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=92,
                        line_number=5,
                        column_number=5,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n        ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=93,
                        line_number=5,
                        column_number=6,
                    ),
                ),
                Token(
                    type=TokenType.SWITCH_KEYWORD,
                    data="switch",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=102,
                        line_number=6,
                        column_number=9,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=108,
                        line_number=6,
                        column_number=15,
                    ),
                ),
                Token(
                    type=TokenType.GET_KEYWORD,
                    data="get",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=109,
                        line_number=6,
                        column_number=16,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_PAREN,
                    data="(",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=112,
                        line_number=6,
                        column_number=19,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"RawPostbackInfo_ThreeType"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=113,
                        line_number=6,
                        column_number=20,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_PAREN,
                    data=")",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=140,
                        line_number=6,
                        column_number=47,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=141,
                        line_number=6,
                        column_number=48,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=142,
                        line_number=6,
                        column_number=49,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=144,
                        line_number=6,
                        column_number=51,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"aaa"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=145,
                        line_number=6,
                        column_number=52,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=150,
                        line_number=6,
                        column_number=57,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_BRACE,
                    data="{",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=151,
                        line_number=6,
                        column_number=58,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n        ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=152,
                        line_number=6,
                        column_number=59,
                    ),
                ),
                Token(
                    type=TokenType.CASE_KEYWORD,
                    data="case",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=161,
                        line_number=7,
                        column_number=9,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=165,
                        line_number=7,
                        column_number=13,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"kochava"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=166,
                        line_number=7,
                        column_number=14,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=175,
                        line_number=7,
                        column_number=23,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=176,
                        line_number=7,
                        column_number=24,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=178,
                        line_number=7,
                        column_number=26,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"bbb"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=179,
                        line_number=7,
                        column_number=27,
                    ),
                ),
                Token(
                    type=TokenType.COMMA,
                    data=",",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=184,
                        line_number=7,
                        column_number=32,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=185,
                        line_number=7,
                        column_number=33,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"min_kochava"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=186,
                        line_number=7,
                        column_number=34,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=199,
                        line_number=7,
                        column_number=47,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=200,
                        line_number=7,
                        column_number=48,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=202,
                        line_number=7,
                        column_number=50,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"cccc"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=203,
                        line_number=7,
                        column_number=51,
                    ),
                ),
                Token(
                    type=TokenType.COLON,
                    data=":",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=209,
                        line_number=7,
                        column_number=57,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n            ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=210,
                        line_number=7,
                        column_number=58,
                    ),
                ),
                Token(
                    type=TokenType.RETURN_KEYWORD,
                    data="return",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=223,
                        line_number=8,
                        column_number=13,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=229,
                        line_number=8,
                        column_number=19,
                    ),
                ),
                Token(
                    type=TokenType.TRANSFORM_KEYWORD,
                    data="transform",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=230,
                        line_number=8,
                        column_number=20,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_PAREN,
                    data="(",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=239,
                        line_number=8,
                        column_number=29,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data="`TODO Kochava`",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=240,
                        line_number=8,
                        column_number=30,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_PAREN,
                    data=")",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=254,
                        line_number=8,
                        column_number=44,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=255,
                        line_number=8,
                        column_number=45,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=256,
                        line_number=8,
                        column_number=46,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=258,
                        line_number=8,
                        column_number=48,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"Kochava MMP"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=259,
                        line_number=8,
                        column_number=49,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=272,
                        line_number=8,
                        column_number=62,
                    ),
                ),
                Token(
                    type=TokenType.COMMENT,
                    data="/// comment2\n",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=273,
                        line_number=8,
                        column_number=63,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="        ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=285,
                        line_number=9,
                        column_number=1,
                    ),
                ),
                Token(
                    type=TokenType.DEFAULT_KEYWORD,
                    data="default",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=293,
                        line_number=9,
                        column_number=9,
                    ),
                ),
                Token(
                    type=TokenType.COLON,
                    data=":",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=300,
                        line_number=9,
                        column_number=16,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n            ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=301,
                        line_number=9,
                        column_number=17,
                    ),
                ),
                Token(
                    type=TokenType.RETURN_KEYWORD,
                    data="return",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=314,
                        line_number=10,
                        column_number=13,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=320,
                        line_number=10,
                        column_number=19,
                    ),
                ),
                Token(
                    type=TokenType.TRANSFORM_KEYWORD,
                    data="transform",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=321,
                        line_number=10,
                        column_number=20,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_PAREN,
                    data="(",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=330,
                        line_number=10,
                        column_number=29,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data="`TODO`",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=331,
                        line_number=10,
                        column_number=30,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=337,
                        line_number=10,
                        column_number=36,
                    ),
                ),
                Token(
                    type=TokenType.PLUS,
                    data="+",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=338,
                        line_number=10,
                        column_number=37,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=339,
                        line_number=10,
                        column_number=38,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='" other"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=340,
                        line_number=10,
                        column_number=39,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_PAREN,
                    data=")",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=348,
                        line_number=10,
                        column_number=47,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=349,
                        line_number=10,
                        column_number=48,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=350,
                        line_number=10,
                        column_number=49,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=352,
                        line_number=10,
                        column_number=51,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"其他MMP"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=353,
                        line_number=10,
                        column_number=52,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n        ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=360,
                        line_number=10,
                        column_number=59,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_BRACE,
                    data="}",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=369,
                        line_number=11,
                        column_number=9,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n    ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=370,
                        line_number=11,
                        column_number=10,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_BRACE,
                    data="}",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=375,
                        line_number=12,
                        column_number=5,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n\n    ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=376,
                        line_number=12,
                        column_number=6,
                    ),
                ),
                Token(
                    type=TokenType.UNIT_KEYWORD,
                    data="unit",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=382,
                        line_number=14,
                        column_number=5,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=386,
                        line_number=14,
                        column_number=9,
                    ),
                ),
                Token(
                    type=TokenType.IDENTIFIER,
                    data="AttributeTypeInfo",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=387,
                        line_number=14,
                        column_number=10,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=404,
                        line_number=14,
                        column_number=27,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=405,
                        line_number=14,
                        column_number=28,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=407,
                        line_number=14,
                        column_number=30,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"归因类型信息"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=408,
                        line_number=14,
                        column_number=31,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n    ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=416,
                        line_number=14,
                        column_number=39,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_BRACE,
                    data="{",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=421,
                        line_number=15,
                        column_number=5,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n        ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=422,
                        line_number=15,
                        column_number=6,
                    ),
                ),
                Token(
                    type=TokenType.IF_KEYWORD,
                    data="if",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=431,
                        line_number=16,
                        column_number=9,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=433,
                        line_number=16,
                        column_number=11,
                    ),
                ),
                Token(
                    type=TokenType.TEST_KEYWORD,
                    data="test",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=434,
                        line_number=16,
                        column_number=12,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_PAREN,
                    data="(",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=438,
                        line_number=16,
                        column_number=16,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"NormalPostbackInfo_MmpNameInfo_Value"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=439,
                        line_number=16,
                        column_number=17,
                    ),
                ),
                Token(
                    type=TokenType.COMMA,
                    data=",",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=477,
                        line_number=16,
                        column_number=55,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=478,
                        line_number=16,
                        column_number=56,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"eq"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=479,
                        line_number=16,
                        column_number=57,
                    ),
                ),
                Token(
                    type=TokenType.COMMA,
                    data=",",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=483,
                        line_number=16,
                        column_number=61,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=484,
                        line_number=16,
                        column_number=62,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"Kochava"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=485,
                        line_number=16,
                        column_number=63,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_PAREN,
                    data=")",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=494,
                        line_number=16,
                        column_number=72,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=495,
                        line_number=16,
                        column_number=73,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=496,
                        line_number=16,
                        column_number=74,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=498,
                        line_number=16,
                        column_number=76,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"aaa"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=499,
                        line_number=16,
                        column_number=77,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=504,
                        line_number=16,
                        column_number=82,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_BRACE,
                    data="{",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=505,
                        line_number=16,
                        column_number=83,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n\n            ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=506,
                        line_number=16,
                        column_number=84,
                    ),
                ),
                Token(
                    type=TokenType.IF_KEYWORD,
                    data="if",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=520,
                        line_number=18,
                        column_number=13,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=522,
                        line_number=18,
                        column_number=15,
                    ),
                ),
                Token(
                    type=TokenType.TEST_KEYWORD,
                    data="test",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=523,
                        line_number=18,
                        column_number=16,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_PAREN,
                    data="(",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=527,
                        line_number=18,
                        column_number=20,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"RawPostbackInfo_HasAttribuType"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=528,
                        line_number=18,
                        column_number=21,
                    ),
                ),
                Token(
                    type=TokenType.COMMA,
                    data=",",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=560,
                        line_number=18,
                        column_number=53,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=561,
                        line_number=18,
                        column_number=54,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"eq"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=562,
                        line_number=18,
                        column_number=55,
                    ),
                ),
                Token(
                    type=TokenType.COMMA,
                    data=",",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=566,
                        line_number=18,
                        column_number=59,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=567,
                        line_number=18,
                        column_number=60,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"true"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=568,
                        line_number=18,
                        column_number=61,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_PAREN,
                    data=")",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=574,
                        line_number=18,
                        column_number=67,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=575,
                        line_number=18,
                        column_number=68,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=576,
                        line_number=18,
                        column_number=69,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=578,
                        line_number=18,
                        column_number=71,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"ccc"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=579,
                        line_number=18,
                        column_number=72,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n               ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=584,
                        line_number=18,
                        column_number=77,
                    ),
                ),
                Token(
                    type=TokenType.LOGICAL_AND,
                    data="&&",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=600,
                        line_number=19,
                        column_number=16,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=602,
                        line_number=19,
                        column_number=18,
                    ),
                ),
                Token(
                    type=TokenType.TEST_KEYWORD,
                    data="test",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=603,
                        line_number=19,
                        column_number=19,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_PAREN,
                    data="(",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=607,
                        line_number=19,
                        column_number=23,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"RawPostbackInfo_AttribuType"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=608,
                        line_number=19,
                        column_number=24,
                    ),
                ),
                Token(
                    type=TokenType.COMMA,
                    data=",",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=637,
                        line_number=19,
                        column_number=53,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=638,
                        line_number=19,
                        column_number=54,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"eq"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=639,
                        line_number=19,
                        column_number=55,
                    ),
                ),
                Token(
                    type=TokenType.COMMA,
                    data=",",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=643,
                        line_number=19,
                        column_number=59,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=644,
                        line_number=19,
                        column_number=60,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='""',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=645,
                        line_number=19,
                        column_number=61,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_PAREN,
                    data=")",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=647,
                        line_number=19,
                        column_number=63,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=648,
                        line_number=19,
                        column_number=64,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=649,
                        line_number=19,
                        column_number=65,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=651,
                        line_number=19,
                        column_number=67,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"ddd"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=652,
                        line_number=19,
                        column_number=68,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=657,
                        line_number=19,
                        column_number=73,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_BRACE,
                    data="{",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=658,
                        line_number=19,
                        column_number=74,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n\n                ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=659,
                        line_number=19,
                        column_number=75,
                    ),
                ),
                Token(
                    type=TokenType.RETURN_KEYWORD,
                    data="return",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=677,
                        line_number=21,
                        column_number=17,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=683,
                        line_number=21,
                        column_number=23,
                    ),
                ),
                Token(
                    type=TokenType.TRANSFORM_KEYWORD,
                    data="transform",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=684,
                        line_number=21,
                        column_number=24,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_PAREN,
                    data="(",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=693,
                        line_number=21,
                        column_number=33,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data="`TODO 0`",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=694,
                        line_number=21,
                        column_number=34,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_PAREN,
                    data=")",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=702,
                        line_number=21,
                        column_number=42,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=703,
                        line_number=21,
                        column_number=43,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=704,
                        line_number=21,
                        column_number=44,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=706,
                        line_number=21,
                        column_number=46,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"非mtg归因 - kochava"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=707,
                        line_number=21,
                        column_number=47,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n            ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=725,
                        line_number=21,
                        column_number=65,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_BRACE,
                    data="}",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=738,
                        line_number=22,
                        column_number=13,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n        ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=739,
                        line_number=22,
                        column_number=14,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_BRACE,
                    data="}",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=748,
                        line_number=23,
                        column_number=9,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n\n        ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=749,
                        line_number=23,
                        column_number=10,
                    ),
                ),
                Token(
                    type=TokenType.COMMENT,
                    data="/// comment3\n",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=759,
                        line_number=25,
                        column_number=9,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="        ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=771,
                        line_number=26,
                        column_number=1,
                    ),
                ),
                Token(
                    type=TokenType.IF_KEYWORD,
                    data="if",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=779,
                        line_number=26,
                        column_number=9,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=781,
                        line_number=26,
                        column_number=11,
                    ),
                ),
                Token(
                    type=TokenType.TEST_KEYWORD,
                    data="test",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=782,
                        line_number=26,
                        column_number=12,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_PAREN,
                    data="(",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=786,
                        line_number=26,
                        column_number=16,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"RawPostbackInfo_AttribuType"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=787,
                        line_number=26,
                        column_number=17,
                    ),
                ),
                Token(
                    type=TokenType.COMMA,
                    data=",",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=816,
                        line_number=26,
                        column_number=46,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=817,
                        line_number=26,
                        column_number=47,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"eq"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=818,
                        line_number=26,
                        column_number=48,
                    ),
                ),
                Token(
                    type=TokenType.COMMA,
                    data=",",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=822,
                        line_number=26,
                        column_number=52,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=823,
                        line_number=26,
                        column_number=53,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"0"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=824,
                        line_number=26,
                        column_number=54,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_PAREN,
                    data=")",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=827,
                        line_number=26,
                        column_number=57,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=828,
                        line_number=26,
                        column_number=58,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=829,
                        line_number=26,
                        column_number=59,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=831,
                        line_number=26,
                        column_number=61,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"eeee"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=832,
                        line_number=26,
                        column_number=62,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=838,
                        line_number=26,
                        column_number=68,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_BRACE,
                    data="{",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=839,
                        line_number=26,
                        column_number=69,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n                ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=840,
                        line_number=26,
                        column_number=70,
                    ),
                ),
                Token(
                    type=TokenType.RETURN_KEYWORD,
                    data="return",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=857,
                        line_number=27,
                        column_number=17,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=863,
                        line_number=27,
                        column_number=23,
                    ),
                ),
                Token(
                    type=TokenType.TRANSFORM_KEYWORD,
                    data="transform",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=864,
                        line_number=27,
                        column_number=24,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_PAREN,
                    data="(",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=873,
                        line_number=27,
                        column_number=33,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data="`TODO 0`",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=874,
                        line_number=27,
                        column_number=34,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_PAREN,
                    data=")",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=882,
                        line_number=27,
                        column_number=42,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=883,
                        line_number=27,
                        column_number=43,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=884,
                        line_number=27,
                        column_number=44,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=886,
                        line_number=27,
                        column_number=46,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"非mtg归因 - 其他"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=887,
                        line_number=27,
                        column_number=47,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n        ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=900,
                        line_number=27,
                        column_number=60,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_BRACE,
                    data="}",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=909,
                        line_number=28,
                        column_number=9,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n\n        ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=910,
                        line_number=28,
                        column_number=10,
                    ),
                ),
                Token(
                    type=TokenType.RETURN_KEYWORD,
                    data="return",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=920,
                        line_number=30,
                        column_number=9,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=926,
                        line_number=30,
                        column_number=15,
                    ),
                ),
                Token(
                    type=TokenType.TRANSFORM_KEYWORD,
                    data="transform",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=927,
                        line_number=30,
                        column_number=16,
                    ),
                ),
                Token(
                    type=TokenType.OPEN_PAREN,
                    data="(",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=936,
                        line_number=30,
                        column_number=25,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data="`TODO 1`",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=937,
                        line_number=30,
                        column_number=26,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_PAREN,
                    data=")",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=945,
                        line_number=30,
                        column_number=34,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=946,
                        line_number=30,
                        column_number=35,
                    ),
                ),
                Token(
                    type=TokenType.AS_KEYWORD,
                    data="as",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=947,
                        line_number=30,
                        column_number=36,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data=" ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=949,
                        line_number=30,
                        column_number=38,
                    ),
                ),
                Token(
                    type=TokenType.STRING_LITERAL,
                    data='"mtg归因"',
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=950,
                        line_number=30,
                        column_number=39,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n    ",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=957,
                        line_number=30,
                        column_number=46,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_BRACE,
                    data="}",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=962,
                        line_number=31,
                        column_number=5,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=963,
                        line_number=31,
                        column_number=6,
                    ),
                ),
                Token(
                    type=TokenType.CLOSE_BRACE,
                    data="}",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=964,
                        line_number=32,
                        column_number=1,
                    ),
                ),
                Token(
                    type=TokenType.WHITESPACE,
                    data="\n",
                    source_location=SourceLocation(
                        file_name="<unnamed>",
                        file_offset=965,
                        line_number=32,
                        column_number=2,
                    ),
                ),
            ],
        )


if __name__ == "__main__":
    unittest.main()
