from dataclasses import dataclass


@dataclass
class TestOpInfo:
    op: str
    reverse_op: str

    multiple_op: str | None = None
    single_op: str | None = None
    min_number_of_values: int = 0
    max_number_of_values: int | None = None
    number_of_subkeys: int = 0


test_op_infos: dict[str, TestOpInfo] = {
    "in": TestOpInfo(
        op="in",
        reverse_op="nin",
        single_op="eq",
        min_number_of_values=1,
    ),
    "nin": TestOpInfo(
        op="nin",
        reverse_op="in",
        single_op="neq",
        min_number_of_values=1,
    ),
    "eq": TestOpInfo(
        op="eq",
        reverse_op="neq",
        multiple_op="in",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "neq": TestOpInfo(
        op="neq",
        reverse_op="eq",
        multiple_op="nin",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "gt": TestOpInfo(
        op="gt",
        reverse_op="lte",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "lte": TestOpInfo(
        op="lte",
        reverse_op="gt",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "lt": TestOpInfo(
        op="lt",
        reverse_op="gte",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "gte": TestOpInfo(
        op="gte",
        reverse_op="lt",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "len_eq": TestOpInfo(
        op="len_eq",
        reverse_op="len_neq",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "len_neq": TestOpInfo(
        op="len_neq",
        reverse_op="len_eq",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "len_gt": TestOpInfo(
        op="len_gt",
        reverse_op="len_lte",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "len_lte": TestOpInfo(
        op="len_lte",
        reverse_op="len_gt",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "len_lt": TestOpInfo(
        op="len_lt",
        reverse_op="len_gte",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "len_gte": TestOpInfo(
        op="len_gte",
        reverse_op="len_lt",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "num_eq": TestOpInfo(
        op="num_eq",
        reverse_op="num_neq",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "num_neq": TestOpInfo(
        op="num_neq",
        reverse_op="num_eq",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "num_gt": TestOpInfo(
        op="num_gt",
        reverse_op="num_lte",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "num_lte": TestOpInfo(
        op="num_lte",
        reverse_op="num_gt",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "num_lt": TestOpInfo(
        op="num_lt",
        reverse_op="num_gte",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "num_gte": TestOpInfo(
        op="num_gte",
        reverse_op="num_lt",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    # ----------
    "v_in": TestOpInfo(
        op="v_in",
        reverse_op="v_nin",
        single_op="v_eq",
        min_number_of_values=1,
    ),
    "v_nin": TestOpInfo(
        op="v_nin",
        reverse_op="v_in",
        single_op="v_neq",
        min_number_of_values=1,
    ),
    "v_eq": TestOpInfo(
        op="v_eq",
        reverse_op="v_neq",
        multiple_op="v_in",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_neq": TestOpInfo(
        op="v_neq",
        reverse_op="v_eq",
        multiple_op="v_nin",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_gt": TestOpInfo(
        op="v_gt",
        reverse_op="v_lte",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_lte": TestOpInfo(
        op="v_lte",
        reverse_op="v_gt",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_lt": TestOpInfo(
        op="v_lt",
        reverse_op="v_gte",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_gte": TestOpInfo(
        op="v_gte",
        reverse_op="v_lt",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_len_eq": TestOpInfo(
        op="v_len_eq",
        reverse_op="v_len_neq",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_len_neq": TestOpInfo(
        op="v_len_neq",
        reverse_op="v_len_eq",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_len_gt": TestOpInfo(
        op="v_len_gt",
        reverse_op="v_len_lte",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_len_lte": TestOpInfo(
        op="v_len_lte",
        reverse_op="v_len_gt",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_len_lt": TestOpInfo(
        op="v_len_lt",
        reverse_op="v_len_gte",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_len_gte": TestOpInfo(
        op="v_len_gte",
        reverse_op="v_len_lt",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_num_eq": TestOpInfo(
        op="v_num_eq",
        reverse_op="v_num_neq",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_num_neq": TestOpInfo(
        op="v_num_neq",
        reverse_op="v_num_eq",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_num_gt": TestOpInfo(
        op="v_num_gt",
        reverse_op="v_num_lte",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_num_lte": TestOpInfo(
        op="v_num_lte",
        reverse_op="v_num_gt",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_num_lt": TestOpInfo(
        op="v_num_lt",
        reverse_op="v_num_gte",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    "v_num_gte": TestOpInfo(
        op="v_num_gte",
        reverse_op="v_num_lt",
        min_number_of_values=1,
        max_number_of_values=1,
    ),
    # ----------
    "x/string/regexp_like": TestOpInfo(
        op="x/string/regexp_like",
        reverse_op="x/string/regexp_unlike",
        min_number_of_values=1,
    ),
    "x/string/regexp_unlike": TestOpInfo(
        op="x/string/regexp_unlike",
        reverse_op="x/string/regexp_like",
        min_number_of_values=1,
    ),
    # ----------
    "x/map/elem_in": TestOpInfo(
        op="x/map/elem_in",
        reverse_op="x/map/elem_nin",
        single_op="x/map/elem_eq",
        min_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_nin": TestOpInfo(
        op="x/map/elem_nin",
        reverse_op="x/map/elem_in",
        single_op="x/map/elem_neq",
        min_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_eq": TestOpInfo(
        op="x/map/elem_eq",
        reverse_op="x/map/elem_neq",
        multiple_op="x/map/elem_in",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_neq": TestOpInfo(
        op="x/map/elem_neq",
        reverse_op="x/map/elem_eq",
        multiple_op="x/map/elem_nin",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_gt": TestOpInfo(
        op="x/map/elem_gt",
        reverse_op="x/map/elem_lte",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_lte": TestOpInfo(
        op="x/map/elem_lte",
        reverse_op="x/map/elem_gt",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_lt": TestOpInfo(
        op="x/map/elem_lt",
        reverse_op="x/map/elem_gte",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_gte": TestOpInfo(
        op="x/map/elem_gte",
        reverse_op="x/map/elem_lt",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_len_eq": TestOpInfo(
        op="x/map/elem_len_eq",
        reverse_op="x/map/elem_len_neq",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_len_neq": TestOpInfo(
        op="x/map/elem_len_neq",
        reverse_op="x/map/elem_len_eq",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_len_gt": TestOpInfo(
        op="x/map/elem_len_gt",
        reverse_op="x/map/elem_len_lte",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_len_lte": TestOpInfo(
        op="x/map/elem_len_lte",
        reverse_op="x/map/elem_len_gt",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_len_lt": TestOpInfo(
        op="x/map/elem_len_lt",
        reverse_op="x/map/elem_len_gte",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_len_gte": TestOpInfo(
        op="x/map/elem_len_gte",
        reverse_op="x/map/elem_len_lt",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_num_eq": TestOpInfo(
        op="x/map/elem_num_eq",
        reverse_op="x/map/elem_num_neq",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_num_neq": TestOpInfo(
        op="x/map/elem_num_neq",
        reverse_op="x/map/elem_num_eq",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_num_gt": TestOpInfo(
        op="x/map/elem_num_gt",
        reverse_op="x/map/elem_num_lte",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_num_lte": TestOpInfo(
        op="x/map/elem_num_lte",
        reverse_op="x/map/elem_num_gt",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_num_lt": TestOpInfo(
        op="x/map/elem_num_lt",
        reverse_op="x/map/elem_num_gte",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/elem_num_gte": TestOpInfo(
        op="x/map/elem_num_gte",
        reverse_op="x/map/elem_num_lt",
        min_number_of_values=2,
        max_number_of_values=2,
        number_of_subkeys=1,
    ),
    "x/map/has_key": TestOpInfo(
        op="x/map/has_key",
        reverse_op="x/map/has_not_key",
        min_number_of_values=1,
        max_number_of_values=1,
        number_of_subkeys=1,
    ),
    "x/map/has_no_key": TestOpInfo(
        op="x/map/has_no_key",
        reverse_op="x/map/has_key",
        min_number_of_values=1,
        max_number_of_values=1,
        number_of_subkeys=1,
    ),
}
